### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by ahanank** [AlkaffAhamed/Tahajjud-Calculator#1]
Is there going to be a release candidate for this? I don’t know how to compile it :/ Looks to be promising though.

**Comment by AlkaffAhamed** [comment]
Hi, 

Thanks a lot for understanding and believing in the potential of this software. However, I am not planning on releasing under releases. Still, I just uploaded the executable in the **"bin" folder**. Currently, I have built it for Windows only. Soon, I will upload the Ubuntu executable also. 

If you want to compile on your own, the steps are quite simple. Install a C/C++ compiler like MingW or CygWin and compile. However, I downloaded the Code::Blocks IDE with compiler. The setup is easier. (I assume you are using Windows)

1) Download and install Code::Blocks from 
http://www.codeblocks.org/downloads/26
64 bit download and install "codeblocks-20.03mingw-setup.exe"
32 bit download and install "codeblocks-20.03mingw-32bit-setup.exe"

2) Open the cpp file with Code::Blocks, build and run. 
either 
Build>Build   (compiles to exe)
or 
Build>Build and Run   (compiles to exe and runs)

The executable will also be created on the same folder as your cpp file. You can double-click to run in windows (or use terminal to run in Ubuntu). 

Please update me when you are successful in running the program or if you encounter other issues. 

Thank you.

**Comment by ahanank** [comment]
MashALLAH brother. I was hoping it would run on my iPhone since it was written in C++ but this would do. May ALLAH reward you for this. Thank you. Coincidently, I was able to run that version you had written in Java last night on my PC as well. Worked wonderfully! Just curious, do you recommend one version over the other? Which one is the latest?

**Comment by AlkaffAhamed** [comment]
Aameen. Please spread to your friends if they are interested. They can take my code and design it for other platform if they are interested. However, please inform me that you have used my code. 

This project was actually my experiment. Both are using the same algorithm, so you can use anything you are comfortable with (or your case, whichever works). The only difference differences are, both are written in different languages and 1.1 has an additional GUI. 

I created this C++ version in my second year to help me calculate the Tahajjud time as I used to be awake those times. In 3rd year, I learnt about designing GUI, so I thought of playing with GUI for this software. It looked like an upgrade, so I called it Tahajjud Calculator 1.1. I decided to share it in GitHub because this will be useful for many of my muslim brothers and sisters.

**Comment by ahanank** [comment]
Will do, InshaAllah. Thank you.
